# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompleteApp', '0004_auto_20161022_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='dueTime',
            field=models.DateTimeField(max_length=50),
        ),
    ]
