# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CompleteApp', '0005_auto_20161022_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='uniqueId',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
