# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 07:47
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompleteApp', '0006_tasks_uniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='color',
            field=colorfield.fields.ColorField(default=b'#FF0000', max_length=10),
        ),
    ]
